# Generated by Django 2.2.1 on 2019-07-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='myquote',
        ),
    ]
