# Generated by Django 2.2.6 on 2019-10-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
